Repository Hack4Eugene/spark-sert2521-2019, pull requests merged in 2019-04, with the labels that each got.

#36 Add parent route
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  docs/api/payments.md
  docs/api/users.md
  frontend/package.json
  frontend/src/components/App.tsx
  frontend/src/index.tsx
  frontend/src/routes/Main.tsx
  frontend/src/state/actions.ts
  frontend/yarn.lock
Labels: wip

#54 Add Circle CI config
  .circleci/config.yml
  Dockerfile
Labels: devops

#72 Add detailed person view
  .idea/misc.xml
  frontend/src/components/AdminSection.tsx
  frontend/src/components/DonationPopup.tsx
  frontend/src/components/HomepageCard.tsx
  frontend/src/components/ItemCard.tsx
  frontend/src/components/PersonDonationButton.tsx
  frontend/src/components/RequestDonationButton.tsx
  frontend/src/index.tsx
  frontend/src/routes/Admin.tsx
  frontend/src/routes/Home.tsx
  frontend/src/routes/Main.tsx
  frontend/src/utilities/getRequests.ts
  frontend/yarn.lock
Labels: ! HIGH PRIORITY !, feature, frontend, wip
